#!/usr/bin/env python3
"""Send a local image file to the configured Hermes Telegram home channel."""

from __future__ import annotations

import argparse
import json
import mimetypes
import os
from pathlib import Path
import sys
import urllib.error
import urllib.request
import uuid


ENV_PATH = Path("/home/hermes/.hermes/.env")


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def build_multipart(fields: dict[str, str], file_field: str, file_path: Path) -> tuple[bytes, str]:
    boundary = "----HermesBoundary" + uuid.uuid4().hex
    content_type = mimetypes.guess_type(file_path.name)[0] or "application/octet-stream"
    body = bytearray()

    for name, value in fields.items():
        body.extend(f"--{boundary}\r\n".encode())
        body.extend(f'Content-Disposition: form-data; name="{name}"\r\n\r\n'.encode())
        body.extend(str(value).encode())
        body.extend(b"\r\n")

    body.extend(f"--{boundary}\r\n".encode())
    body.extend(
        f'Content-Disposition: form-data; name="{file_field}"; filename="{file_path.name}"\r\n'.encode()
    )
    body.extend(f"Content-Type: {content_type}\r\n\r\n".encode())
    body.extend(file_path.read_bytes())
    body.extend(f"\r\n--{boundary}--\r\n".encode())

    return bytes(body), boundary


def main() -> int:
    parser = argparse.ArgumentParser(description="Send an image to the Hermes Telegram home channel.")
    parser.add_argument("image_path", help="Path to a local PNG/JPG/WebP image generated by Hermes.")
    parser.add_argument("caption", nargs="?", default="", help="Optional Telegram caption.")
    parser.add_argument("--chat-id", default="", help="Override Telegram chat ID. Defaults to TELEGRAM_HOME_CHANNEL.")
    args = parser.parse_args()

    load_env_file(ENV_PATH)

    token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = args.chat_id or os.environ.get("TELEGRAM_HOME_CHANNEL")
    image_path = Path(args.image_path).expanduser().resolve()

    if not token:
        print("ERROR: TELEGRAM_BOT_TOKEN is not configured.", file=sys.stderr)
        return 1
    if not chat_id:
        print("ERROR: TELEGRAM_HOME_CHANNEL is not configured.", file=sys.stderr)
        return 1
    if not image_path.exists() or not image_path.is_file():
        print(f"ERROR: image file not found: {image_path}", file=sys.stderr)
        return 1

    fields = {"chat_id": chat_id}
    if args.caption:
        fields["caption"] = args.caption

    body, boundary = build_multipart(fields, "photo", image_path)
    request = urllib.request.Request(
        f"https://api.telegram.org/bot{token}/sendPhoto",
        data=body,
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
    )

    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            result = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        print(f"ERROR: Telegram sendPhoto failed with HTTP {exc.code}.", file=sys.stderr)
        return 1
    except urllib.error.URLError as exc:
        print(f"ERROR: Telegram sendPhoto failed: {exc.reason}.", file=sys.stderr)
        return 1

    if not result.get("ok"):
        print("ERROR: Telegram sendPhoto failed.", file=sys.stderr)
        return 1

    message_id = result.get("result", {}).get("message_id")
    print(json.dumps({"ok": True, "message_id": message_id, "image": str(image_path)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
