#!/usr/bin/env python3
"""Send a local image file to the configured Hermes Telegram home channel."""

from __future__ import annotations

import argparse
import json
import mimetypes
import os
from pathlib import Path
import stat
import sys
import urllib.error
import urllib.request
import uuid


ENV_PATH = Path("/home/hermes/.hermes/.env")
EXIT_OK = 0
EXIT_CONFIG = 2
EXIT_DESTINATION = 3
EXIT_INPUT = 4
EXIT_NETWORK = 5
EXIT_REMOTE = 6


class InputValidationError(ValueError):
    """Raised when the selected upload is not a safe supported image."""


class ConfigurationError(ValueError):
    """Raised when two configuration sources disagree."""


def load_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def configured_value(name: str, file_values: dict[str, str]) -> str:
    environment_value = os.environ.get(name, "").strip()
    file_value = file_values.get(name, "").strip()
    if environment_value and file_value and environment_value != file_value:
        raise ConfigurationError(f"conflicting values for {name}")
    return environment_value or file_value


def _path_has_symlink(path: Path) -> bool:
    absolute = path if path.is_absolute() else Path.cwd() / path
    current = Path(absolute.anchor)
    for part in absolute.parts[1:]:
        current /= part
        if current.is_symlink():
            return True
    return False


def validate_image_file(raw_path: str) -> tuple[Path, str]:
    selected = Path(raw_path).expanduser()
    if _path_has_symlink(selected):
        raise InputValidationError("symbolic links are not accepted")
    try:
        resolved = selected.resolve(strict=True)
        file_stat = resolved.stat()
    except (OSError, RuntimeError) as exc:
        raise InputValidationError("image is unavailable") from exc
    if not stat.S_ISREG(file_stat.st_mode):
        raise InputValidationError("input is not a regular file")
    if file_stat.st_size <= 0:
        raise InputValidationError("image is empty")

    lowered_parts = {part.casefold() for part in resolved.parts}
    lowered_name = resolved.name.casefold()
    if (
        ".ssh" in lowered_parts
        or lowered_name == ".env"
        or lowered_name.startswith(".env.")
        or lowered_name in {"authorized_keys", "id_rsa", "id_ed25519", "credentials"}
    ):
        raise InputValidationError("sensitive paths are not valid image inputs")

    try:
        with resolved.open("rb") as handle:
            header = handle.read(16)
    except OSError as exc:
        raise InputValidationError("image cannot be read") from exc

    if header.startswith(b"\x89PNG\r\n\x1a\n"):
        image_type = "png"
        valid_suffixes = {".png"}
    elif header.startswith(b"\xff\xd8\xff"):
        image_type = "jpeg"
        valid_suffixes = {".jpg", ".jpeg"}
    elif len(header) >= 12 and header[:4] == b"RIFF" and header[8:12] == b"WEBP":
        image_type = "webp"
        valid_suffixes = {".webp"}
    else:
        raise InputValidationError("file content is not a supported image")
    if resolved.suffix.casefold() not in valid_suffixes:
        raise InputValidationError("image extension does not match its content")
    return resolved, image_type


def build_multipart(fields: dict[str, str], file_field: str, file_path: Path) -> tuple[bytes, str]:
    boundary = "----HermesBoundary" + uuid.uuid4().hex
    content_type = mimetypes.guess_type(file_path.name)[0] or "application/octet-stream"
    body = bytearray()

    for name, value in fields.items():
        body.extend(f"--{boundary}\r\n".encode())
        body.extend(f'Content-Disposition: form-data; name="{name}"\r\n\r\n'.encode())
        body.extend(str(value).encode())
        body.extend(b"\r\n")

    body.extend(f"--{boundary}\r\n".encode())
    body.extend(
        f'Content-Disposition: form-data; name="{file_field}"; filename="{file_path.name}"\r\n'.encode()
    )
    body.extend(f"Content-Type: {content_type}\r\n\r\n".encode())
    body.extend(file_path.read_bytes())
    body.extend(f"\r\n--{boundary}--\r\n".encode())

    return bytes(body), boundary


def main(argv: list[str] | None = None, *, opener=None, env_path: Path | None = None) -> int:
    parser = argparse.ArgumentParser(description="Send an image to the Hermes Telegram home channel.")
    parser.add_argument("image_path", help="Path to a local PNG/JPG/WebP image generated by Hermes.")
    parser.add_argument("caption", nargs="?", default="", help="Optional Telegram caption.")
    parser.add_argument("--chat-id", default="", help="Destination override; it must match TELEGRAM_HOME_CHANNEL.")
    parser.add_argument("--dry-run", action="store_true", help="Validate configuration and input without network access.")
    args = parser.parse_args(argv)

    try:
        file_values = load_env_file(env_path or ENV_PATH)
        token = configured_value("TELEGRAM_BOT_TOKEN", file_values)
        allowed_chat_id = configured_value("TELEGRAM_HOME_CHANNEL", file_values)
    except (OSError, ConfigurationError):
        print("ERROR: Telegram configuration is invalid.", file=sys.stderr)
        return EXIT_CONFIG
    chat_id = args.chat_id or allowed_chat_id

    if not token:
        print("ERROR: TELEGRAM_BOT_TOKEN is not configured.", file=sys.stderr)
        return EXIT_CONFIG
    if not allowed_chat_id:
        print("ERROR: TELEGRAM_HOME_CHANNEL is not configured.", file=sys.stderr)
        return EXIT_CONFIG
    if not chat_id or chat_id != allowed_chat_id:
        print("ERROR: Telegram destination is not authorized.", file=sys.stderr)
        return EXIT_DESTINATION
    try:
        image_path, image_type = validate_image_file(args.image_path)
    except InputValidationError:
        print("ERROR: input is not an authorized PNG/JPEG/WebP image.", file=sys.stderr)
        return EXIT_INPUT

    if args.dry_run:
        print(json.dumps({"ok": True, "dry_run": True, "image_type": image_type}))
        return EXIT_OK

    fields = {"chat_id": chat_id}
    if args.caption:
        fields["caption"] = args.caption

    body, boundary = build_multipart(fields, "photo", image_path)
    request = urllib.request.Request(
        f"https://api.telegram.org/bot{token}/sendPhoto",
        data=body,
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
    )

    transport = opener or urllib.request.urlopen
    try:
        with transport(request, timeout=60) as response:
            result = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError:
        print("ERROR: Telegram rejected the simulated or real request.", file=sys.stderr)
        return EXIT_REMOTE
    except (urllib.error.URLError, TimeoutError, OSError):
        print("ERROR: Telegram transport failed.", file=sys.stderr)
        return EXIT_NETWORK
    except (UnicodeDecodeError, json.JSONDecodeError):
        print("ERROR: Telegram returned an invalid response.", file=sys.stderr)
        return EXIT_REMOTE

    if not result.get("ok"):
        print("ERROR: Telegram sendPhoto failed.", file=sys.stderr)
        return EXIT_REMOTE

    message_id = result.get("result", {}).get("message_id")
    print(json.dumps({"ok": True, "message_id": message_id, "image": str(image_path)}, ensure_ascii=False))
    return EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
